# Generated by Django 2.2.12 on 2021-11-30 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
